name: publish
on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            accept-flake-config = true

      - uses: cachix/cachix-action@12
        with:
          name: nxios-iso
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix flake check -L
      - run: nix build -L
